server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://MUSICAPPLICATION
          predicates:
            - Path=/auth**
        - id: registration-service
          uri: lb://MUSICAPPLICATION
          predicates:
            - Path=/auth/**
        - id: song-service
          uri: lb://MUSICAPPLICATION
          predicates:
            - Path=/song/**
        - id: playlist-service
          uri: lb://MUSICAPPLICATION
          predicates:
            - Path=/playlist/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

