spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:${db.port:5432}/music_application
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
